Bugfix when try to define gruntfile property, and that has already been defined.
/home/eduardo/.nvm/v0.10.28/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:150
  Object.defineProperty(this, 'gruntfile', {
         ^
TypeError: Cannot redefine property: gruntfile
    at Function.defineProperty (native)
    at EntityGenerator.Base (/home/eduardo/.nvm/v0.10.28/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/base.js:150:10)